server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notebook-db
    username: admin
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true


###Maybe worth changing
    hibernate:
      ddl-auto: update